### ISSUE TITLE
ogg stream not playing 

### ISSUE THREAD

**Issue by enakhi** [ybrid/player-sdk-swift#2]
can you check this stream:
https://stream.radioparadise.com/flacm
library reads metadata but not playing anything 

here is the log file:
[log_radio.text.zip](https://github.com/ybrid/player-sdk-swift/files/8309981/log_radio.text.zip)

**Comment by FlorianAtNacamar** [comment]
This stream contains ogg/FLAC. FLAC support is in the project's backlog. 
By now FLAC native is already playing but FLAC in ogg container is not.

**Comment by enakhi** [comment]
Thanks for your answer and your library ☺️
